build:
    dependencies:
        before:
            - pip install antlr4-python3-runtime
            - pip install httplib2
            - pip install cleo
            - pip install coverage
    tests:
        override:
            -
                command: coverage run -m unittest discover -s test -p *Test.py
                coverage:
                    file: '.coverage'
                    config_file: '.coveragerc'
                    format: 'py-cc'

checks:
    python:
        code_rating: true
        duplicate_code: true

filter:
    excluded_paths:
        - test/*
        - sdoc/antlr/*

tools:
    pylint:
        python_version: '3'
        config_file: pylintrc
