language: python
python:
  - '3.4'
  - '3.5'
  - '3.5-dev'
  - 'nightly'

sudo: true

install:
  - cd $HOME
  - pip3 install antlr4-python3-runtime

script: 
  - cd $TRAVIS_BUILD_DIR
  - python3 -m unittest test/*.py
